### PR TITLE
Write sublime syntax file for GLSL

### PR DESCRIPTION
**Pull request by rwols**
This pull request adds a sublime syntax file for GLSL.

I just copied over the syntax file from C and removed things that were not applicable to GLSL, and added the keywords etc from the tmLanguage file.

### CODE REVIEW

**Comment by euler0** [comment]
@rwols Thanks for your PRs and suggestions. I will review and merge them soon!

**Comment by rwols** [comment]
I notice now that the goto-label handling can go away too, I'll have to push more commits.
I also think that strings can go away, but I'd like to keep highlighting the #include statements. I know #include is not officially a preprocessor keyword, but lots of shader files use it anyway, so it's nice to highlight that. Anyway please do not merge this yet as I'll push more commits.

**Comment by rwols** [comment]
Okay, I'm satisfied with this pull request now, you can review/merge it if you like!

schermafbeelding 2017-07-13 om 12 37 44

**Comment by euler0** [comment]
This is an amazing work, @rwols!

Does .sublime-syntax always have a priority when .tmLanguage files are co-exist?
(I can’t remove GLSL.tmLanguage file because GitHub.com uses the file for its syntax highlighting.)

**Comment by rwols** [comment]
Yes, sublime-syntax files take priority. So GLSL.tmLanguage and GLSL.sublime-syntax can coexist in the same folder.

**Comment by rwols** [comment]
Thanks mate, I'll be submitting one for ESSL soon.

**Comment by rwols** [comment]
It looks like ESSL.tmLanguage is quite outdated. I will base my changes on [this document](https://www.khronos.org/registry/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.pdf).

**Pull request merged**
