### PR TITLE
Fixed minor typo of gl_FragData and gl_FragDepth.

### PR DESCRIPTION
**Pull request by minalear**

### CODE REVIEW

**Comment by rwols** [comment]
Are you still on ST2?

**Comment by minalear** [comment]
I'm actually use visual studio code, but I found similar typos for the extension I use there.  So I thought I would find similar issues in other repos.

**Comment by rwols** [comment]
All new versions of ST should automatically load [this file](https://github.com/euler0/sublime-glsl/blob/master/GLSL.sublime-syntax), but I'm sure someone out there still has use for this!

**Comment by minalear** [comment]
Oh wow, yea I just literally googled "gl_FragDat" to find similar issues.  Hopefully someone finds this useful haha.

**Comment by euler0** [comment]
Okay, thanks for your fix, @minalear! :)

**Pull request merged**
